Update protobuf to 3.6.1
hunter-packages/protobuf pull request #8
Opened 2018-12-06 01:16 UTC by rbsheth

@ruslo Lots of the cherry-picked commits for the 3.5.2 Hunterization are already in the 3.6 branch, so I simply added only the hunterization commit via a rebase.

Needs a new branch in hunter-packages/protobuf, probably hunter-3.6.x or hunter-3.6.1.

2018-12-06 08:48 UTC, ruslo requested changes
> Needs a new branch in hunter-packages/protobuf, probably hunter-3.6.x or hunter-3.6.1.

I've created branch `hunter-3.6.1` from upstream tag `v3.6.1`.

2018-12-06 08:48 UTC, ruslo commented on BUILD
> +load(":compiler_config_setting.bzl", "create_compiler_config_setting")
> I simply added only the hunterization commit via a rebase

I think you pull changes that we don't need. I'm expecting only CMake code touched, see previous hunterization:
* https://github.com/hunter-packages/protobuf/pull/7/files

2018-12-06 18:17 UTC, rbsheth commented
@ruslo there are a number of backported fixes to the branch post 3.6.1 release: https://github.com/protocolbuffers/protobuf/commits/3.6.x

Some of them are quite important, such as Python 3.7 compatibility. Should we make a new version for this? Something like 3.6.1-b829ff2 or 3.6.x-b829ff2?

2018-12-07 11:18 UTC, ruslo approved these changes

2018-12-07 11:19 UTC, ruslo commented
> Some of them are quite important, such as Python 3.7 compatibility

Okay, I see

> Something like 3.6.1-b829ff2 or 3.6.x-b829ff2?

Yes, branch hunter-3.6.x-b829ff2 created

2018-12-07 11:19 UTC, merged

2018-12-07 11:20 UTC, ruslo commented
Released: https://github.com/hunter-packages/protobuf/releases/tag/v3.6.x-b829ff2-p0